from django.urls import path
from . import views
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('trangchu',views.index),
    path('',views.index),
    path('thongkechung',views.index2),
    path('thongkengay',views.index3),
    path('thongkethang',views.index4),
    path('thongkenam',views.index5),
    path('xemdulieu',views.index6),
    
    # path url xu li thong ke
    path('ketquachung',views.xltk_chung),
    path('ketquangay',views.xltk_ngay),
    path('ketquathang',views.xltk_thang),
    path('ketquanam',views.xltk_nam),


    # path url xu li api trong ngay
    path('angiang',views.angiang),
    path('brvt',views.brvt),
    path('bacgiang',views.bacgiang),
    path('backan',views.backan),
    path('baclieu',views.baclieu),
    path('bacninh',views.bacninh),
    path('bentre',views.bentre),
    path('binhdinh',views.binhdinh),
    path('binhduong',views.binhduong),
    path('binhphuoc',views.binhphuoc),
    path('binhthuan',views.binhthuan),
    path('camau',views.camau),
    path('cantho',views.cantho),
    path('caobang',views.caobang),
    path('danang',views.danang),
    path('daklak',views.daklak),
    path('daknong',views.daknong),
    path('dienbien',views.dienbien),
    path('dongnai',views.dongnai),
    path('dongthap',views.dongthap),
    path('gialai',views.gialai),
    path('hagiang',views.hagiang),
    path('hanam',views.hanam),
    path('hanoi',views.hanoi),
    path('hatinh',views.hatinh),
    path('haiduong',views.haiduong),
    path('haiphong',views.haiphong),
    path('haugiang',views.haugiang),
    path('hoabinh',views.hoabinh),
    path('hungyen',views.hungyen),
    path('khanhhoa',views.khanhhoa),
    path('kiengiang',views.kiengiang),
    path('kontum',views.kontum),
    path('laichau',views.laichau),
    path('lamdong',views.lamdong),
    path('langson',views.langson),
    path('laocai',views.laocai),
    path('longan',views.longan),
    path('namdinh',views.namdinh),
    path('nghean',views.nghean),
    path('ninhbinh',views.ninhbinh),
    path('ninhthuan',views.ninhthuan),
    path('phutho',views.phutho),
    path('phuyen',views.phuyen),
    path('quangbinh',views.quangbinh),
    path('quangnam',views.quangnam),
    path('quangngai',views.quangngai),
    path('quangninh',views.quangninh),
    path('quangtri',views.quangtri),
    path('soctrang',views.soctrang),
    path('sonla',views.sonla),
    path('tayninh',views.tayninh),
    path('thaibinh',views.thaibinh),
    path('thainguyen',views.thainguyen),
    path('thanhhoa',views.thanhhoa),
    path('thuathienhue',views.thuathienhue),
    path('tiengiang',views.tiengiang),
    path('hcm',views.hcm),
    path('travinh',views.travinh),
    path('tuyenquang',views.tuyenquang),
    path('vinhlong',views.vinhlong),
    path('vinhphuc',views.vinhphuc),
    path('yenbai',views.yenbai),
    


]
